cmake_minimum_required(VERSION 3.20)
project(Chess98 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# ban `cmake .` in /
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR)
    message(FATAL_ERROR "cmake . in / is not allowed")
endif()

add_executable(Chess98 src/main.cpp)
target_include_directories(Chess98 PRIVATE ${CMAKE_SOURCE_DIR}/src)

if(MSVC)
    target_compile_options(Chess98 PRIVATE /W3 /permissive- /Zc:__cplusplus)
else()
    target_compile_options(Chess98 PRIVATE -Wpedantic)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        target_compile_options(Chess98 PRIVATE -O3 -ffast-math -DNDEBUG)
    elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        target_compile_options(Chess98 PRIVATE -O2 -g -DNDEBUG)
    else()
        target_compile_options(Chess98 PRIVATE -g -O0)
    endif()
endif()
